  - name: add user "node_exporter"
    user: 
      name: node_exporter 
      home: "{{ node_exporter_home_dir }}" 
    become: True

  - name: Download node_exporter
    get_url: 
       url:  "{{ node_exporter_download_url }}"
       dest: "{{ node_exporter_download_location }}"
    become: True

  - name: Extract node_exporter archive
    unarchive:
      src: "{{ node_exporter_download_location }}"
      dest: "{{ node_exporter_home_dir }}"
      owner: node_exporter
      group: node_exporter
      remote_src: yes
      extra_opts: "--strip-components=1"
    become: True

  - name: Copy bin file
    ansible.builtin.copy:
      src: "{{ node_exporter_src_bin_file }}"
      dest: "{{ node_exporter_dest_bin_file }}"
      mode: 0755
      remote_src: yes
      owner: node_exporter
      group: node_exporter
    become: True

  - name: Copy node_exporter service file
    template:
      src: "{{ node_exporter_service_template_file }}"
      dest: "{{ node_exporter_service_file }}"
    become: True

  - name: Start and enable node_exporter
    service:
      daemon_reload: yes
      name: node_exporter
      state: started
      enabled: yes
    when: ansible_service_mgr == "systemd"
    become: True
